"""first revision

Revision ID: db5fa71f9490
Revises: de87c7c67077
Create Date: 2024-01-12 00:21:43.671557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db5fa71f9490'
down_revision = 'de87c7c67077'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
